#include "structures.h"

Plugin_Config_Structure Plugin_Config;
ValidNick_Structure ValidNick_Config;
NickLength_Structure NickLength_Config;
RepeatedNicks_Structure RepeatedNicks_Config;
PlayerConnectionInfo PlayerInfo[MAX_PLAYERS];